name: Release Gem

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2 # Adjust this to your preferred Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: bundle exec rake test # Adjust this if you use a different test command

    - name: Build gem
      run: gem build *.gemspec

    - name: Push to GitHub Packages
      run: |
        gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}