name: Release Gem

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2 # Adjust this to your preferred Ruby version
        bundler-cache: false

    - name: Install dependencies
      run: |
        gem install bundler

    - name: Unfreeze bundler
      run: bundle config set frozen false
      
    - name: Update Gemfile.lock
      run: bundle update
      
    - name: Install dependencies
      run: bundle install

    #- name: Run tests
    #  run: bundle exec rake test # Adjust this if you use a different test command

    - name: Build gem
      run: gem build *.gemspec

    - name: Push to GitHub Packages
      run: |
        GEM_NAME=$(ls *.gem | head -n 1)
        OWNER="${GITHUB_REPOSITORY_OWNER}"
        GITHUB_TOKEN="${{ secrets.GITHUB }}"
        
        RESPONSE=$(curl -s -u "${OWNER}:${GITHUB_TOKEN}" -H "Content-Type: application/octet-stream" --data-binary @"${GEM_NAME}" "https://rubygems.pkg.github.com/${OWNER}/api/v1/gems")
        
        if echo "$RESPONSE" | grep -q '"success":true'; then
          echo "Successfully pushed ${GEM_NAME} to GitHub Packages"
        else
          echo "Failed to push ${GEM_NAME} to GitHub Packages"
          echo "Response: $RESPONSE"
          exit 1
        fi
 
    - name: Push to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        GEM_NAME=$(ls *.gem | head -n 1)
        gem push $GEM_NAME
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}