name: Run Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install dependencies
      run: |
          gem install bundler
  
    - name: Unfreeze bundler
      run: bundle config set frozen false
        
    - name: Update Gemfile.lock
      run: bundle update
        
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: |
        bundle exec rake test | tee test_output.log
    - name: Parse test results
      run: |
        echo "TEST_RESULTS=$(ruby -e '
          log = File.read("test_output.log")
          runs = log.scan(/(\d+) runs/).flatten.map(&:to_i).sum
          assertions = log.scan(/(\d+) assertions/).flatten.map(&:to_i).sum
          failures = log.scan(/(\d+) failures/).flatten.map(&:to_i).sum
          errors = log.scan(/(\d+) errors/).flatten.map(&:to_i).sum
          skips = log.scan(/(\d+) skips/).flatten.map(&:to_i).sum
          puts "#{runs} runs, #{assertions} assertions, #{failures} failures, #{errors} errors, #{skips} skips"
        ')" >> $GITHUB_ENV
    - name: Create test results badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ac922546bfc70590e78705eeeaaa0c76
        filename: test_results.json
        label: Tests
        message: ${{ env.TEST_RESULTS }}
        color: ${{ env.TEST_RESULTS == '0 runs, 0 assertions, 0 failures, 0 errors, 0 skips' && 'yellow' || env.TEST_RESULTS == '' && 'red' || contains(env.TEST_RESULTS, 'failures') || contains(env.TEST_RESULTS, 'errors') && 'red' || 'green' }}